### ISSUE TITLE
Moving to HTTPS

### ISSUE THREAD

**Issue by szepeviktor** [Matty9191/ssl-cert-check#15]
Hello @Matty9191 !

> Digital certificates have become an essential part of Internet commerce, and are widely used to verify the identity of clients and servers.

Would you mind moving http://prefetch.net/ to https?

**Comment by Matty9191** [comment]
I've actually been working on that for the past couple of weeks. Need to get off Wordpress first.

**Comment by szepeviktor** [comment]
I run WordPress sites only, I am a maintenance guy.
If you need someone to be the housekeeper
Click https://github.com/szepeviktor/debian-server-tools/blob/master/CV.md

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by Matty9191** [comment]
The site was moved to a Let's Encrypt certification this morning. Thanks for the suggestion.

**Comment by szepeviktor** [comment]
+1 https://www.ssllabs.com/ssltest/analyze.html?d=prefetch.net
