### ISSUE TITLE
Request: timeout

### ISSUE THREAD

**Issue by avacam** [Matty9191/ssl-cert-check#17]
Please add support for setting a timeout for the openssl s_client command to improve the handling of unreachable addresses.

Something like this would work:

TIMEOUT=$(which timeout)
... ${TIMEOUT} ${intTimeout} ${OPENSSL} s_client ...

**Comment by Matty9191** [comment]
Nice suggestion but the timeout utility (actually coreutils) isn't available on a number of platforms. I currently run the script under timeout's control and use an || to notify me of issues. Thanks for the suggestion!
