### ISSUE TITLE
Sender should not default to 'postmaster'

### ISSUE THREAD

**Issue by tlhackque** [Matty9191/ssl-cert-check#20]
When sending mail, the latest version defaults From to 'postmaster@localhost.localdomain'.

This is incompatible with previous versions (which let the mailer default to the user running ssl-cert-check), and is a misuse of 'postmaster'.

Postmaster is reserved for mail issues, and is not a good default for ssl-cert-check.  Mail to/from Postmaster is likely to be routed differently from SSL administrators.

localhost.localdomain creates problems when the destination is someplace else - and worse, doesn't identify the host from which the mail is sent.

Suggest using nothing (as before, let the mailer default to the user & host running the script.)  Or if you must, use $LOGNAME or $USER and $HOSTNAME to construct a default sender.  HOSTNAME is a bashishm, & some non-POSIX systems use USER so you may need something like this to be safe:
 [ -z "$HOSTNAME" ] && HOSTNAME="`hostname`"
 [ -z "$HOSTNAME" ] && HOSTNAME="`uname -n`"
 [ -z "$LOGNAME" ] && LOGNAME="$USER"
 [ -z "$LOGNAME" ] && LOGNAME="root"
 SENDER="$LOGNAME@$HOSTNAME"

But **I recommend just letting the mailer do its thing** - that way any mailer configuration (e.g. user-specific dotfile or wrapper around the mailer) won't be displaced.  

Thus: initialize SENDER to "", and only include the "from" option if it's set.

**Comment by Matty9191** [comment]
That's a valid concern. I reverted the SENDER to "" to match previous versions.
