### ISSUE TITLE
Temp files not always cleaned up

### ISSUE THREAD

**Issue by tlhackque** [Matty9191/ssl-cert-check#21]
I have seen temp files (cert.* & error.*) left in /var/tmp under some circumstances.
   For example:

    # ./ssl-cert-check  glorp.foo
    Usage: ./ssl-cert-check [ -e email address ] [-E sender email address] [ -x days ] [-q] [-a] [-b] [-h] [-i] [-n] [-N] [-v]
           { [ -s common_name ] && [ -p port] } || { [ -f cert_file ] } || { [ -c cert file ] } || { [ -d cert dir ] }

      -a                : Send a warning message through E-mail
    [snip]
      -x days           : Certificate expiration interval (eg. if cert_date < days)

    # ls -l /var/tmp
    total 4
    -rw------- 1 user user    0 Nov 15 10:36 cert.A11263
    -rw------- 1 user user    0 Nov 15 10:36 error.v11264

Patch:
````
--- ssl-cert-check.base 2017-11-15 06:37:29.000000000 -0500
+++ ssl-cert-check      2017-11-15 10:37:06.000000000 -0500
@@ -869,10 +869,15 @@

 # Place to stash temporary files
 CERT_TMP=$($MKTEMP /var/tmp/cert.XXXXXX)
 ERROR_TMP=$($MKTEMP /var/tmp/error.XXXXXX)

+cleanup() {
+  [ $DEBUG == 1 ] || rm -f ${CERT_TMP} ${ERROR_TMP}
+}
+trap cleanup EXIT INT TERM QUIT
+
 ### Baseline the dates so we have something to compare to
 MONTH=$(${DATE} "+%m")
 DAY=$(${DATE} "+%d")
 YEAR=$(${DATE} "+%Y")
 NOWJULIAN=$(date2julian ${MONTH#0} ${DAY#0} ${YEAR})
````

**Comment by Matty9191** [comment]
Excellent suggestion! I added this to version 4.9 and credited you with the enhancement. Thanks!!

**Comment by cynial** [comment]
ERROR: The file named /var/tmp/cert.2ORjAz is unreadable or doesn't exist
---
It seems still not cleaned up
