### ISSUE TITLE
ubuntu 18.04 reporting incorrect expiry date

### ISSUE THREAD

**Issue by deon609** [Matty9191/ssl-cert-check#31]
Hi, After upgrading to Ubuntu 18.04 from 16.04 the expiry days are reporting incorrectly. All showing up as 618 days. It is working fine on other 16.04 servers

**Comment by Matty9191** [comment]
Can you share the name of a domain that's triggering this? I just ran several tests on an Ubuntu 18.04 machine and don't see any issues.

**Comment by Matty9191** [comment]
Closing due to no feedback.
