### ISSUE TITLE
mail subject change

### ISSUE THREAD

**Issue by billjamzz** [Matty9191/ssl-cert-check#33]
not an issue but a suggestion.
The line:
                  | ${MAIL} -s "WARNING: SSL CERT for ${HOST} \"(CN: ${COMMONNAME})\" will expire in ${WARNDAYS}-days or less" ${ADMIN}

If you change "${WARNDAYS}-days or less" to "${CERTDIFF}-days" you can tell from the subject what day the cert will expire.
This was helpful for our environment.
We really like the script btw.  Thank you for sharing it!

**Comment by Matty9191** [comment]
Excellent suggestion! The script was updated.
