### ISSUE TITLE
pkcs12 hardcodes pass:

### ISSUE THREAD

**Issue by mortya** [Matty9191/ssl-cert-check#39]
I'm looking to monitor a pkcs12 file.  I have a password in a file  Unfortunately, the ssl-cert-check -k option wants me to put the password in the command-line, where it will be exposed in various ways; this is frowned on in the openssl manpage.  Easy fix would be to just remove pass: from the ssl-cert-check openssl call, but that would break backwards compatibility.

**Comment by Matty9191** [comment]
If you want to provide better security (always a good thing) you can use the env:variable syntax to pass in the password. Adding this to the script will break existing implementations so unfortunately I won't be able to do that. :( Great suggestion though!
