### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by affinityv** [Matty9191/ssl-cert-check#41]
Current Version text (3.30), doesn't match latest revision history version (3.31)

**Comment by kbabioch** [comment]
See: https://github.com/Matty9191/ssl-cert-check/blob/698c1996d05152cfaf2a1a3df4cc70482411fac8/ssl-cert-check#L11

**Comment by Matty9191** [comment]
Thanks for the note. This was addressed in version 4.1.
