### ISSUE TITLE
Please change -v or -V to output script version

### ISSUE THREAD

**Issue by wowcut** [Matty9191/ssl-cert-check#43]
Besides looking into the source I do not see any possibility of getting the version number of this script. 
It is good practice for unix tools to provide a -v or -V option that will print out the version number.
This is needed e.g. when older versions of the script have errors and you want to check if the newest version is available, when using this script from your own scripts. E.g. any version below 1.31 gave wrong results for SNI domains, but are still in many distros, what increases the possibility that on different distros you get wrong results for an ssl expiry check. I am using a small wrapper for that to workaround this bug.
Thanks.

**Comment by Matty9191** [comment]
You can print the version now with "-V":

$ ssl-cert-check -V
4.1
