### ISSUE TITLE
Script from your website

### ISSUE THREAD

**Issue by Karting06** [Matty9191/ssl-cert-check#5]
Hello,

I tested your script from your website http://prefetch.net/articles/checkcertificate.html. But it isn't up to date...  
Maybe it could be better to change the link or to update it on your website?

Thanks for the script,
Karting06

**Comment by Matty9191** [comment]
Thanks for the heads up. I moved the script to github a while back:

https://github.com/Matty9191/ssl-cert-check

I'll get the link on that page updated.

Thanks again!
- Ryan
http://prefetch.net

**Comment by Karting06** [comment]
You're welcome. I thank you for the script :)
