### ISSUE TITLE
ERROR: The file named /var/tmp/cert.Y3yZfo is unreadable or doesn't exist

### ISSUE THREAD

**Issue by ejazhashmi** [Matty9191/ssl-cert-check#60]
Hi I have 30 domains in the list and when i run the following command 

ssl-cert-check -a -f /home/ddevops/status/ssldomains

Getting this error 
ERROR: The file named /var/tmp/cert.Y3yZfo is unreadable or doesn't exist

Regards
Syed Ejaz

**Comment by ejazhashmi** [comment]
Moreover is there any limits of domains ?

**Comment by debmind** [comment]
I am also getting the same problem, how to resolve this?

**Comment by Matty9191** [comment]
Can you send me one or domains that are triggering this error? This typically occurs because openssl was unable to create the file or extract the certificate.

**Comment by ejazhashmi** [comment]
@Matty9191 my issue was resolve, there was an extra space in the list of domains 📟

**Comment by tsaukam** [comment]
I'm getting the same issue when using Cygwin. Not sure if Cygwin is supported or not but ssl-cert-check is a nice tool for us who's batching on Windows and needing something to lookup cert expiry. 

For testing, I've created a list and added www.yahoo.com 443 and www.google.com 443 (line-by-line), it will resolve the first cert but the subsequent site will fail.

Host                                Issuer            Status   Expires     Days
----------------------------------- ----------------- -------- ----------- ----
ERROR: The file named /var/tmp/cert.5CxH0r is unreadable or doesn't exist
 is validease check to make sure the certificate for www.yahoo.com:443
www.google.com:443                  Google Trust Serv Valid    Mar 30 2021   57

**Comment by tsaukam** [comment]
Disregard. Found the solution. 
Have to convert the list i.e. ssldomains from DOS format to Unix format.

**Comment by gilbertosoareslopes** [comment]
Hello,
I am also getting the same problem, how to resolve this?

**Comment by Seoptics** [comment]
> Found the solution. Have to convert the list i.e. ssldomains from DOS format to Unix format.
> 
> Using notepad++ Edit -> EOL Conversion -> Unix (LF)

That was the solution for me, many thanks
